# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  ### MATCH
  desc "Fastlane Match"
  lane :match_all do
    match_development
  end
  
  desc "Fastlane Match - Development"
  private_lane :match_development do
    match(
      app_identifier: "maxime.maheo.free.fr.Tonight-s-Movie",
      type: "development",
      git_url: "git@github.com:mmaheo/certificates.git",
      username: "maxime.maheo@gmail.com",
      force_for_new_devices: true
    )
  end
end
